// Ping request
http://localhost:8080/ping

###
// Read user by id
http://localhost:8080/users/1

###
http://localhost:8080/users/2

###
http://localhost:8080/users/notid

###
// Create User
POST http://localhost:8080/users

{
  "first_name": "Rajesh",
  "last_name": "Reddy",
  "email_id": "rajesh.reddy@test.com"
}